version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=product_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/product_db --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mongodb_data:
